### ISSUE TITLE
Error when adding a comment in a SCSS file

### ISSUE THREAD

**Issue by drawcard** [whoisthecoon/atom-block-comment-plus#1]
Uncaught TypeError: Cannot read property 'includes' of undefined
/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:810
Hide Stack Trace
TypeError: Cannot read property 'includes' of undefined
    at searchCommentRow (/Users/Drawcard/.atom/packages/block-comment-plus/lib/block-comment-plus.js:114:18)
    at /Users/Drawcard/.atom/packages/block-comment-plus/lib/block-comment-plus.js:41:26
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:805:18)
    at atom-text-editor.toggle (/Users/Drawcard/.atom/packages/block-comment-plus/lib/block-comment-plus.js:17:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at module.exports._executeCallback (/Users/Drawcard/.atom/packages/tool-bar/lib/tool-bar-button-view.coffee:69:23)
    at space-pen-button.<anonymous> (/Users/Drawcard/.atom/packages/tool-bar/lib/tool-bar-button-view.coffee:29:7)
    at space-pen-button.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-button.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)

**Comment by drawcard** [comment]
It seems to happen when doing the following:

1) Placing the text cursor point after a line that contains a // before it, in a SCSS file - eg:
```// Someone's comment``` ``][```
2) Toggling the Block Comment via menu

**Comment by whoisthecoon** [comment]
Fixed, thank you!
